### PR TITLE
Add disabling of wifi LED

### LINKED ISSUE #1: wifi light control?
wifi light control?

### PR DESCRIPTION
**Pull request by ioncorimenia**
Fixes #1

### CODE REVIEW

**Comment by Spaqin** [comment]
Hey,

I'd argue that settings A and B as buttons for doing anything is bad design, as the user could be holding A from launching the app and do something he didn't want to do - and that's why I set Power LED buttons as X and Y. But now I remembered how long it takes for the console to boot up a simple program like this and tbh it's not an issue. 

I'll merge it.

Oh, and expect a release some time later - I'm doing stuff on Windows now, Linux will have to wait :^)

**Comment by ioncorimenia** [comment]
Yeah, since it was such a simple program I was thinking about making this into an applet. But then I realized applets don't show up in the HOME menu and there's no other easy ways to run them without exiting your current software.

Also if you want I can attach a release. But honestly I want to try adding something else first.

**Comment by ioncorimenia** [comment]
[bipolar-3ds.zip](https://github.com/Spaqin/bipolar-3ds/files/658835/bipolar-3ds.zip)

**Comment by Spaqin** [comment]
Did you add something else there? I'm not running homebrew code without source :C 

I'll add you to collaborators so you don't need to do a pull request again.

**Comment by ioncorimenia** [comment]
@Spaqin I didn't add anything else, that was just a build. I'll upload it to releases.

**Pull request merged**
